plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.brott.dev/' }
}

dependencies {
    implementation 'com.acmerobotics.roadrunner:MeepMeep:0.1.7'
}

tasks.register('run', JavaExec) {
    group = 'application'
    description = 'Runs the Road Runner 1.0 MeepMeep visualizer.'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.example.meepmeeptesting.MeepMeepTesting'
}
